import "./globals.css";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
     
        <div className="flex w-screen flex-col gap-28 justify-center items-center">
          <div className="flex flex-col w-[1216px]  items-center justify-center gap-48">
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
}
