import "./globals.css";

import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="flex w-screen flex-col items-center">
          <Header />
          <div className="flex flex-col w-[1920px] items-center  gap-48">
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
